version: '3'

services:
  # JobBoard app service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles:/JobPostingApi/staticfiles
    depends_on:
      - db
      - redis
    command: ["./entrypoint.sh"]
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  # PostgreSQL database service
  db:
    image: postgres:latest
    volumes:
      - "./.local/postgres:/var/lib/postgresql/data:delegated"  # Change $PWD to ./ for Windows
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  # Redis service
  redis:
    image: redis:latest
    command: ["redis-server", "--port", "${REDIS_PORT}"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
