# Generated by Django 5.0.7 on 2024-08-03 09:08

import talentpool.apps
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentpool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='uuid',
            field=talentpool.apps.UUIDAutoField(default=uuid.uuid4, editable=False, primary_key=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='uuid',
            field=talentpool.apps.UUIDAutoField(default=uuid.uuid4, editable=False, primary_key=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=talentpool.apps.UUIDAutoField(default=uuid.uuid4, editable=False, primary_key=True, unique=True),
        ),
    ]
